# Generated by Django 3.1.5 on 2021-01-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210110_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tags',
        ),
    ]
