# Generated by Django 3.1.5 on 2021-01-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='tags',
            new_name='tag',
        ),
    ]
