# Generated by Django 3.1.5 on 2021-01-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20210110_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tags',
        ),
    ]
